plugins {
    id 'java'
    id 'application'
}

group = 'com.webapp'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'mysql:mysql-connector-java:8.0.33'
}

application {
    mainClass = 'com.webapp.Main'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
