plugins {
    id 'java'
    id 'application'
}

group = 'com.webapp'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

application {
    mainClass = 'com.webapp.Main'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test{
    useJUnitPlatform()
}
